//! Offline regeneration of `scene_embeddings_precomputed.rs` in the ACTIVE CLIP
//! text-encoder space. Run AFTER swapping the CLIP model (MobileCLIP-S2 →
//! ViT-B/32) with the new `clip_text.onnx` + `vocab.json`/`merges.txt` installed
//! at the canonical path (`%LOCALAPPDATA%\FileID\Models\clip_text\`). Writes the
//! engine-root `scene_embeddings_precomputed.rs` (the file `scene_vocab.rs`
//! `include!`s). Must run from the engine crate dir.
//!   $env:ORT_DYLIB_PATH = "<repo>\platforms\windows\build\runtime-cache\ort-directml-1.22.0\runtimes\win-x64\native\onnxruntime.dll"
//!   cargo run --example gen_scene_matrix --target x86_64-pc-windows-msvc

use std::fmt::Write as _;

use fileid_engine::models::clip_text::{self, ClipText};
use fileid_engine::models::scene_vocab::{SceneLabeler, SCENE_LABELS};
use fileid_engine::models::ClipTokenizer;

fn main() -> anyhow::Result<()> {
    tracing_subscriber::fmt()
        .with_env_filter(tracing_subscriber::EnvFilter::new("info"))
        .init();

    // Construct the text encoder exactly as commands/embed.rs does.
    let weights = clip_text::default_weights_path()?;
    let dir = weights.parent().expect("clip_text weights have a parent dir");
    let vocab = std::fs::read_to_string(dir.join("vocab.json"))?;
    let merges = std::fs::read_to_string(dir.join("merges.txt"))?;
    let tokenizer = ClipTokenizer::new(&vocab, &merges)?;
    let mut model = ClipText::load(&weights, tokenizer)?;

    // Same algorithm the runtime scorer uses (embed templates → average → renorm).
    let labeler = SceneLabeler::build(&mut model)?;
    let matrix = labeler.matrix();
    assert_eq!(matrix.len(), SCENE_LABELS.len(), "matrix rows != label count");
    let dim = matrix[0].len();
    assert_eq!(dim, 512, "expected 512-d CLIP embeddings, got {dim}");
    for (i, row) in matrix.iter().enumerate() {
        let n: f32 = row.iter().map(|x| x * x).sum::<f32>().sqrt();
        assert!((n - 1.0).abs() < 1e-3, "row {i} ({}) not unit-norm: {n}", SCENE_LABELS[i]);
    }

    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by `cargo run --example gen_scene_matrix`. Do not hand-edit.\n");
    out.push_str("// One L2-normalized, prompt-ensembled CLIP-text embedding per\n");
    out.push_str("// scene_vocab::SCENE_LABELS entry, in the ACTIVE CLIP text-encoder space\n");
    out.push_str("// (OpenAI/OpenCLIP ViT-B/32). Regenerate whenever the CLIP model changes.\n");
    writeln!(out, "pub static SCENE_EMBEDDINGS: &[[f32; {dim}]] = &[").unwrap();
    for row in matrix {
        out.push_str("    [");
        for (j, v) in row.iter().enumerate() {
            if j > 0 {
                out.push_str(", ");
            }
            // {:?} prints the shortest round-tripping f32 literal (always with a
            // decimal point or exponent → valid in a [f32; N] literal).
            write!(out, "{v:?}").unwrap();
        }
        out.push_str("],\n");
    }
    out.push_str("];\n");

    std::fs::write("scene_embeddings_precomputed.rs", &out)?;
    eprintln!(
        "wrote {} labels × {} dims → scene_embeddings_precomputed.rs ({} bytes)",
        matrix.len(),
        dim,
        out.len()
    );
    Ok(())
}
