// Custom entry point for the WinUI 3 unpackaged desktop app.
//
// Why we replace the XAML-generated Main:
//   1. Run the WinAppSDK bootstrapper before XAML touches anything. Unpackaged
//      apps need DynamicDependency.Bootstrap to find + load the matching
//      framework package; without it XAML's first ComWrappers call fails.
//   2. Single-instance gate via a named mutex. A second launch surfaces the
//      first window instead of spawning a duplicate process — matches the
//      macOS pattern where a second `open FileID.app` reuses the running app.
//
// DISABLE_XAML_GENERATED_MAIN=true in the .csproj turns off the autogenerated
// Main; this file is the canonical entrypoint.

using Microsoft.UI.Dispatching;
using Microsoft.UI.Xaml;
using Microsoft.Windows.ApplicationModel.DynamicDependency;
using System.Threading;
using WinRT;

namespace FileID;

internal static class Program
{
    /// <summary>
    /// Single-instance mutex name. Per-machine (not per-user) to keep the
    /// behavior deterministic across UAC elevation states. The GUID is opaque
    /// — never reuse it for anything else.
    /// </summary>
    private const string SingleInstanceMutexName = "Global\\FileID-Singleton-{8C9D7C2E-3B87-4F19-8F3F-5A1A1B5E8A8E}";

    [STAThread]
    private static int Main(string[] args)
    {
        // Single-instance gate. Hold the mutex for the lifetime of the
        // process — `using` ensures it releases on any exit path.
        using var instanceMutex = new Mutex(initiallyOwned: true, name: SingleInstanceMutexName, out bool createdNew);
        if (!createdNew)
        {
            // Another FileID is already running. Phase 1 ships a hard exit;
            // Phase 8 polish wires up SetForegroundWindow on the existing
            // instance so the user gets the running window raised.
            return 0;
        }

        // Bootstrap the Windows App SDK runtime. Required for unpackaged
        // framework-dependent apps; the bootstrapper finds the framework
        // package on the user's machine and wires it into the activation
        // context. MUST match the WinAppSDK package version pinned in
        // Directory.Packages.props — 1.7 = 0x00010007.
        if (!Bootstrap.TryInitialize(0x00010007u, out int hr))
        {
            ShowFatalDialog(
                "Windows App SDK runtime not found",
                $"FileID needs the Windows App SDK 1.7 runtime to launch. " +
                $"Install it via:\n\n  winget install Microsoft.WindowsAppRuntime.1.7\n\n" +
                $"Error code: 0x{hr:X8}"
            );
            return hr;
        }

        try
        {
            ComWrappersSupport.InitializeComWrappers();
            Application.Start(parameters =>
            {
                // Bridge the WinUI dispatcher into the modern .NET
                // SynchronizationContext so `await` resumes on the UI thread
                // by default. Required for clean XAML data binding from
                // background tasks (engine event stream, model installer, etc).
                var ctx = new DispatcherQueueSynchronizationContext(DispatcherQueue.GetForCurrentThread());
                SynchronizationContext.SetSynchronizationContext(ctx);
                _ = new App();
            });
        }
        finally
        {
            Bootstrap.Shutdown();
        }

        return 0;
    }

    /// <summary>
    /// Win32 MessageBox for fatal pre-XAML errors. Local-only surface; never
    /// transmits.
    /// </summary>
    private static void ShowFatalDialog(string title, string message)
    {
        // P/Invoke kept inline rather than a helper class — only used here.
        // 0x10 = MB_ICONERROR
        _ = NativeMessageBox(System.IntPtr.Zero, message, title, 0x10u);
    }

    [System.Runtime.InteropServices.DllImport("user32.dll", EntryPoint = "MessageBoxW", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
    private static extern int NativeMessageBox(System.IntPtr hWnd, string text, string caption, uint type);
}
