// Custom entry point for the WinUI 3 unpackaged desktop app.
//
// Why we replace the XAML-generated Main:
//   1. Run the WinAppSDK bootstrapper before XAML touches anything. Unpackaged
//      apps need DynamicDependency.Bootstrap to find + load the matching
//      framework package; without it XAML's first ComWrappers call fails.
//   2. Single-instance gate via a named mutex. A second launch surfaces the
//      first window instead of spawning a duplicate process — matches the
//      macOS pattern where a second `open FileID.app` reuses the running app.
//
// DISABLE_XAML_GENERATED_MAIN=true in the .csproj turns off the autogenerated
// Main; this file is the canonical entrypoint.

using Microsoft.UI.Dispatching;
using Microsoft.UI.Xaml;
using Microsoft.Windows.ApplicationModel.DynamicDependency;
using System.Threading;
using WinRT;

namespace FileID;

internal static class Program
{
    /// <summary>
    /// Single-instance mutex name. Per-machine (not per-user) to keep the
    /// behavior deterministic across UAC elevation states. The GUID is opaque
    /// — never reuse it for anything else.
    /// </summary>
    private const string SingleInstanceMutexName = "Global\\FileID-Singleton-{8C9D7C2E-3B87-4F19-8F3F-5A1A1B5E8A8E}";

    /// <summary>harness hook. When the app is launched with
    /// <c>--auto-scan-folder &lt;path&gt;</c>, App.OnLaunched dispatches a
    /// StartScanAsync against that path once EngineClient reaches Ready.
    /// Enables build/gui-regression.ps1 to drive an end-to-end scan from
    /// the command line without user input. Local-only; no telemetry.</summary>
    public static string? AutoScanFolder { get; private set; }

    /// <summary>paired with <see cref="AutoScanFolder"/>. When set,
    /// the app closes its main window after ScanCompleteEvent fires, which
    /// runs the normal shutdown path (MarkCleanExit) so the harness can
    /// assert clean_exit=true.</summary>
    public static bool AutoExitAfterScan { get; private set; }

    [STAThread]
    private static int Main(string[] args)
    {
        // Parse the harness flags before any other startup. Strict shapes;
        // a lone flag without a value (auto-scan-folder) is ignored.
        for (int i = 0; i < args.Length; i++)
        {
            if (args[i] == "--auto-scan-folder" && i + 1 < args.Length && !string.IsNullOrWhiteSpace(args[i + 1]))
            {
                AutoScanFolder = args[i + 1];
            }
            else if (args[i] == "--auto-exit-after-scan")
            {
                AutoExitAfterScan = true;
            }
        }

        // Single-instance gate. Hold the mutex for the lifetime of the
        // process — `using` ensures it releases on any exit path.
        using var instanceMutex = new Mutex(initiallyOwned: true, name: SingleInstanceMutexName, out bool createdNew);
        if (!createdNew)
        {
            // Another FileID is already running. Hard exit; later polish
            // could SetForegroundWindow on the existing instance.
            return 0;
        }

        // Bootstrap the Windows App SDK runtime. Required for unpackaged
        // framework-dependent apps; the bootstrapper finds the framework
        // package on the user's machine and wires it into the activation
        // context. MUST match the WinAppSDK package version pinned in
        // Directory.Packages.props — 1.7 = 0x00010007.
        if (!Bootstrap.TryInitialize(0x00010007u, out int hr))
        {
            ShowFatalDialog(
                "Windows App SDK runtime not found",
                $"FileID needs the Windows App SDK 1.7 runtime to launch. " +
                $"Install it via:\n\n  winget install Microsoft.WindowsAppRuntime.1.7\n\n" +
                $"Error code: 0x{hr:X8}"
            );
            return hr;
        }

        // Startup-trace: every step of the launch path writes to a small
        // file so when the app "opens then closes" we can diagnose without
        // a debugger attached. Cleared at the start of each launch.
        var traceLogPath = System.IO.Path.Combine(
            System.Environment.GetFolderPath(System.Environment.SpecialFolder.LocalApplicationData),
            "FileID", "logs", "startup-trace.txt");
        try
        {
            System.IO.Directory.CreateDirectory(System.IO.Path.GetDirectoryName(traceLogPath)!);
            System.IO.File.WriteAllText(traceLogPath, $"{System.DateTime.UtcNow:O} startup begin\n");
        }
        catch { /* trace is best-effort */ }

        void Trace(string msg)
        {
            try { System.IO.File.AppendAllText(traceLogPath, $"{System.DateTime.UtcNow:O} {msg}\n"); }
            catch { /* swallow */ }
        }

        try
        {
            Trace("ComWrappersSupport.InitializeComWrappers");
            ComWrappersSupport.InitializeComWrappers();
            Trace("Application.Start");
            Application.Start(parameters =>
            {
                try
                {
                    // Bridge the WinUI dispatcher into the modern .NET
                    // SynchronizationContext so `await` resumes on the UI thread
                    // by default. Required for clean XAML data binding from
                    // background tasks (engine event stream, model installer, etc).
                    Trace("SynchronizationContext bridge");
                    var ctx = new DispatcherQueueSynchronizationContext(DispatcherQueue.GetForCurrentThread());
                    SynchronizationContext.SetSynchronizationContext(ctx);
                    Trace("new App()");
                    _ = new App();
                    Trace("Application.Start callback returned");
                }
                catch (System.Exception inner)
                {
                    Trace($"FATAL inside Application.Start: {inner}");
                    throw;
                }
            });
            Trace("Application.Start returned (clean exit)");
        }
        catch (System.Exception ex)
        {
            Trace($"FATAL outside Application.Start: {ex}");
            ShowFatalDialog("FileID failed to start",
                $"FileID hit an unhandled exception during startup. The full trace is at:\n\n" +
                $"{traceLogPath}\n\n" +
                $"Error:\n{ex.GetType().Name}: {ex.Message}\n\n" +
                $"{ex.StackTrace}");
            return 1;
        }
        finally
        {
            Trace("Bootstrap.Shutdown");
            Bootstrap.Shutdown();
            Trace("end");
        }

        return 0;
    }

    /// <summary>
    /// Win32 MessageBox for fatal pre-XAML errors. Local-only surface; never
    /// transmits.
    /// </summary>
    private static void ShowFatalDialog(string title, string message)
    {
        // P/Invoke kept inline rather than a helper class — only used here.
        // 0x10 = MB_ICONERROR
        _ = NativeMessageBox(System.IntPtr.Zero, message, title, 0x10u);
    }

    [System.Runtime.InteropServices.DllImport("user32.dll", EntryPoint = "MessageBoxW", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
    private static extern int NativeMessageBox(System.IntPtr hWnd, string text, string caption, uint type);
}
